name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types:    [ labeled ]

jobs:
  test:
    runs-on: WSL
    steps:
      - name : test
        run  : |
          echo "Hello World!"

  build:
    runs-on: WSL
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Run test 0
      run: |
        echo "Hello World!"
        ./.ci/runner.py .ci/example.json test-id-0 LOCAL
    
    - name : Remove 'test' label
      if : ${{ github.event.label.name == 'test' }}
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        curl \
          -X DELETE \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: token ${{ github.token }}' \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels/test
  