name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:    [ labeled ]

jobs:
  build:
    # https://stackoverflow.com/a/62331521
    if : ${{ github.event.label == 'test' }}
    runs-on: WSL
    steps:
    - uses: actions/checkout@v3
    - name: Run test 0
      run: |
        echo "Hello World!"
        ./.ci/runner.py .ci/example.json test-id-0 LOCAL

  label-remove:
    if : ${{ github.event.label == 'test' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: test
    