name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types:    [ labeled ]

jobs:
  build:
    # https://stackoverflow.com/a/62331521
    if : ${{ github.event.label == 'test' }}
    runs-on: WSL
    steps:
    - uses: actions/checkout@v3
    - name: Run test 0
      run: |
        echo "Hello World!"
        ./.ci/runner.py .ci/example.json test-id-0 LOCAL

  label-remove:
    if : ${{ github.event.label == 'test' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name : Remove 'test' label
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        curl \
          -X DELETE \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: token ${{ github.token }}' \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels/test
    