name: Regression Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - "**.ipynb"
  pull_request:
    types:    [ labeled ]
    paths-ignore:
      - "**.md"
      - "**.ipynb"

jobs:
  regsuite:
    if : ${{ github.event.label.name == 'test' }} || ${{ github.event_name == 'push' }}
    name: "Run Regression Suite"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Run test 00_01
      run: |
        ./tests/00_*/00_01*
    
    - name: Run test 00_02
      run: |
        ./tests/00_*/00_02*
      
    - name: Run test 00_03
      run: |
        ./tests/00_*/00_03*
    
    - name: Run test 00_04
      run: |
        ./tests/00_*/00_04*
    
    - name: Run test 00_05
      run: |
        ./tests/00_*/00_05*
    
    - name: Run test 00_06
      run: |
        ./tests/00_*/00_06*
    
    - name: Run test 00_07
      run: |
        ./tests/00_*/00_07*
    
    - name: Run test 00_08
      run: |
        ./tests/00_*/00_08*
    
    - name: Run test 00_09
      run: |
        ./tests/00_*/00_09*
    
    - name: Run test 00_10
      run: |
        ./tests/00_*/00_10*
    
    - name: Run test 02_00
      run: |
        ./tests/00_*/02_00*

    - name: Run test 02_01
      run: |
        ./tests/00_*/02_01*

  removeLabel:
    if : ${{ !cancelled() && github.event.label.name == 'test' }}
    name: "Remove Test Label"
    needs: [ regsuite ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name : Remove 'test' label
      if : ${{ !cancelled() && github.event.label.name == 'test' }}
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        curl \
          -X DELETE \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: token ${{ github.token }}' \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels/test
  